# Generated by Django 4.2.6 on 2023-12-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aha', '0003_alter_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.TextField(null=True),
        ),
    ]
